# Generated by Django 5.0.7 on 2024-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_alter_category_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=False),
        ),
    ]
