# Generated by Django 5.0.7 on 2024-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_comment_is_provide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=True),
        ),
    ]
