# Generated by Django 5.0.7 on 2024-08-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0008_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
